theme: jekyll-theme-hacker
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Harjit Nar's CV

##### Table of Contents  
[Things I Can Do](#thingsIcando)  
[Technical Experience](#technicalExperience)
[On The Side](#OnTheSide)  
[Languages](#Languages) 
[Education](#Education) 
